export enum PermissionsENUM {
    GETCOMPANY = 'getcompany',
    MODIFYCOMPANY = 'modifycompany',
    CREATECOMPANY = 'createcompany',
    GETTHEME = 'gettheme',
    MODIFYTHEME = 'modifytheme',
    GETDEVELOPMENTCYCLE = 'getdevelopmentcycle',
    MODIFYDEVELOPMENTCYCLE = 'modifydevelopmentcycle',
    GETSCORINGCRITERIA = 'getscoringcriteria',
    MODIFYSCORINGCRITERIA = 'modifyscoringcriteria',
    GETSEGMENT = 'getsegment',
    MODIFYSEGMENT = 'modifysegment',
    GETTEAM = 'getteam',
    MODIFYTEAM = 'modifyteam',
    GETFTE = 'getfte',
    MODIFYFTE = 'modifyfte',
    GETCONCEPT = 'getconcept',
    MODIFYCONCEPT = 'modifyconcept',
    USERADMIN = 'useradmin',
    UNIVERSALADMIN = 'universaladmin',
}
